-- Synaptic Database Schema
-- This is a consolidated view of all migrations
-- DO NOT RUN THIS FILE DIRECTLY - Use the individual migration files instead

-- Note: This file is automatically generated from the migrations folder
-- To apply migrations, use: supabase db push
-- To generate TypeScript types, use: supabase gen types typescript --local

-- Migrations included:
-- 001_enable_extensions.sql
-- 002_create_users_tables.sql
-- 003_create_notes_tables.sql
-- 004_create_ai_tables.sql
-- 005_create_indexes.sql